import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';

import "./about.scss";

export default function About() {
  return (
    <section id='about-section'>
      <Container className='aboutContainer'>
        <Row className='about-row'><Col><div className="calvin-image"></div></Col><Col><h2>Calvin Hall</h2><p>"Hey, I'm calvin! I'm a software developer. I've been writing software for about 10 years now. My prefered language is Java, but I enjoy programming in almost any language. Aside from languages, I've also spent a considerable amount of time studying computer science, especially topics like data structures, algorithms, object oriented design patterns... basically everything. Typically, I prefer to work on the back-end, but front-end or full-stack is not a problem either. I tend to get along well with others, and am more than happy to spread the knowledge. My biggest problem is that I can easily get side-tracked from the main objective. All too often will I look at code and think, "there's gotta be a better way to do this", and then I'll spend the next half hour, maybe a few hours, possibly even days, trying out solutions to the "problem", when honestly it might already be as good as it can get. I wouldn't say this is an actual problem, but it is something I enjoy doing. I really enjoy programming, as I've been doing it for fun for 10 years, so getting paid to work with code is a dream come true."</p></Col></Row> 
        <Row className='about-row'><Col><h2>James Zobian</h2><p>"Before I attended DeltaV I had some experience in C# back from when I was first starting to dabble in code when I was 13 or 14 and beginning to experiment with game mods and development. In my early twenties I started playing around with HTML and CSS to get more familiarized with web-design. My goal with DeltaV first and foremost was to expand my knowledge in coding and hone my skillset. After I graduate, professionally, I would like to pursue a career in web/software-development. Personally, I would like to get back into home-brewing classic feeling RPG’s with a more in-depth working knowledge. I feel that DeltaV is the best option to pursue what I’m interested in as there are very intelligent like-minded individuals who are working towards similar goals. The small and personal class also allows us to get to know each other pretty well which is great for making lasting connections."</p></Col><Col><div className="james-image"></div></Col></Row>
        <Row className='about-row'><Col><div className="juicy-image"></div></Col><Col><h2>Jacob Wendt</h2><p>"My name is Jacob Wendt and I'm a brand new full-stack developer. The past year I've been a student at DeltaV Code School learning the ins and outs of web development. During my time I've grown substantially as a developer and team member. Not only have I learned valuable web development skills I learned Agile, how to work in a team, and other non development related career skills. In the future I plan to continue to further my knowledge and hone my skills. Ultimately I hope to find a career that will allow me to challenge myself."</p></Col></Row>
        <Row className='about-row'><Col><h2>Jon Schwamman</h2><p>"Hey, I’m Jon, a full stack JavaScript developer and soon to be DeltaV graduate. Prior to learning code I graduated from the University of Northern Iowa in 2016 with a bachelors in Economics. I worked at US Cellular from summer 2016 though summer of 2019. I started as a customer service representative but quickly moved to technical support where I worked for the past 2 years. My previous experience with troubleshooting and problem solving was one of the main drivers for me pick up programming. I enjoy working through difficult issues and love the rush when I’m finally able to solve it. I’m currently wrapping up a 20 week program through DeltaV Code School, a fast-paced web development program in Cedar Rapids, IA, which has helped me gain experience not only in the technical aspects of coding but also working with teams and other coders on a variety of projects."</p></Col><Col><div className="jon-image"></div></Col></Row>
        <Row className='about-row'><Col><div className="jacob-image"></div></Col><Col><h2>Jacob Swenson</h2><p>"Hello all, my name is Jacob Swenson and before programming l I was working as an Industrial electrician. After that job I was told about Delta V code school and have always wanted to do something with technology and it seemed like a great opportunity to explore this field. Delta V has helped me learn the necessary skills to make it in career of  software development. Those skills combined with my past experience in customer service and problem solving has prepared me to enter this industry. I've really enjoyed my time at Delta V and am looking forward to finding a fulfilling career in software development."</p></Col></Row>
      </Container>
    </section>
  );
}


